### ISSUE TITLE
needs-the-cstdint-header

### ISSUE THREAD

**Issue by odeneriksson** [dotse/bbk#12]
Hi,

On latest Fedora 38 the code won't build unless fixing it like so:

From 195bacebd6d9690ab882c061ddec12306fb3b3a7 Mon Sep 17 00:00:00 2001
From: Oden Eriksson <oe@nux.se>
Date: Fri, 4 Aug 2023 15:52:47 +0200
Subject: [PATCH] needs the cstdint header

---
 src/http/httphost.h | 1 +
 src/http/sha1.h     | 1 +
 2 files changed, 2 insertions(+)

diff --git a/src/http/httphost.h b/src/http/httphost.h
index e42da3d..336aae8 100644
--- a/src/http/httphost.h
+++ b/src/http/httphost.h
@@ -4,6 +4,7 @@
 #pragma once
 
 #include <string>
+#include <cstdint>
 
 class CookieManager;
 
diff --git a/src/http/sha1.h b/src/http/sha1.h
index 96480cf..db53478 100644
--- a/src/http/sha1.h
+++ b/src/http/sha1.h
@@ -6,6 +6,7 @@
 
 #include <iostream>
 #include <string>
+#include <cstdint>
 
 void base64_encode(const unsigned char *src, size_t len, char *destination);
 
-- 
2.41.0

Cheers,

**Comment by odeneriksson** [comment]
The patch was scrambled. Sorry.

**Comment by odeneriksson** [comment]
[0001-needs-the-cstdint-header.patch.txt](https://github.com/dotse/bbk/files/12261599/0001-needs-the-cstdint-header.patch.txt)

**Comment by initgoran** [comment]
Thanks. Fixed in https://github.com/dotse/bbk/commit/c61751c49ed40d4646b6cc9c9463e1bd4e2a3c77 .
