### ISSUE TITLE
Potential code missing in src/framework/engine.h

### ISSUE THREAD

**Issue by Djangoooooo** [dotse/bbk#4]
When I tried to compile in Linux I got this error:

`
In file included from ../http/../framework/eventloop.h:21,
                 from ../http/../framework/task.h:36,
                 from ../http/../framework/bridgetask.h:39,
                 from ../http/websocketbridge.h:9,
                 from main.cpp:11:
../http/../framework/engine.h:112:16: error: 'fd_set' has not been declared
  112 |     int setFds(fd_set &r, fd_set &w, fd_set &e);
      |                ^~~~~~
../http/../framework/engine.h:112:27: error: 'fd_set' has not been declared
  112 |     int setFds(fd_set &r, fd_set &w, fd_set &e);
      |                           ^~~~~~
../http/../framework/engine.h:112:38: error: 'fd_set' has not been declared
  112 |     int setFds(fd_set &r, fd_set &w, fd_set &e);
      |                                      ^~~~~~
../http/../framework/engine.h:116:22: error: 'fd_set' does not name a type
  116 |     void doFds(const fd_set &r, const fd_set &w, const fd_set &e, int max);
      |                      ^~~~~~
../http/../framework/engine.h:116:39: error: 'fd_set' does not name a type
  116 |     void doFds(const fd_set &r, const fd_set &w, const fd_set &e, int max);
      |                                       ^~~~~~
../http/../framework/engine.h:116:56: error: 'fd_set' does not name a type
  116 |     void doFds(const fd_set &r, const fd_set &w, const fd_set &e, int max);
      |           `

I solved this by adding this header in the engine.h file: `#include <sys/select.h>`

I tried compiling it in both Alpine Linux and Ubuntu and it did not work, but when I added this piece of code it worked. It could be something wrong on my end, but I figured there might also be something wrong with the code.

**Comment by initgoran** [comment]
> I solved this by adding this header in the engine.h file: `#include <sys/select.h>`

You are complete right. Since fd_sed is referenced in engine.h, we must include sys/select.h there
(cf. https://github.com/initgoran/bbk/commit/95002e2fb308e597de26beca47633595cd8b787c)
