### ISSUE TITLE
Running bbk_cli on Unifi access points

### ISSUE THREAD

**Issue by pv2b** [dotse/bbk#6]
Hello!

To try to avoid the "XY Problem", my goal is to run bbk_cli on a Unifi Access point. This will let me do a speed-test on a remote LAN without having to remote-control a specific PC, which can be useful for troubleshooting purposes. (We already do this on some FreeBSD-based open source firewalls with great results, thanks for that!)

So I looked at bbk_cli's pre-compiled binaries. You have binaries for many operating systems and architectures. Unfortunately, the supplied pre-compiled binaries do not work on Unifi access points. These APs are basically just embedded MIPS Linux boxes. From my investigation, it would seem that the problem is that this embedded device does not have ld.so.1.

```
login as: Admin
Admin@192.168.98.63's password:


BusyBox v1.25.1 () built-in shell (ash)


  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2020
 |   |  |   |  \  ||  \   |  |   Ubiquiti Networks, Inc.
 |______|___|  /__||__/   |__|
            |_/                  https://www.ui.com/

      Welcome to UniFi UAP-AC-Pro-Gen2!

UAP-AC-Proe870-BZ.v4.3.28# uname -a
Linux UAP-AC-Proe870 4.4.153 #0 Thu Aug 30 12:10:54 2018 mips GNU/Linux
UAP-AC-Proe870-BZ.v4.3.28# curl https://frontend.bredbandskollen.se/download/bbk
_cli_linux_mips-1.0 -o /tmp/bbk_cli
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  495k  100  495k    0     0   117k      0  0:00:04  0:00:04 --:--:--  118k
UAP-AC-Proe870-BZ.v4.3.28# chmod +x /tmp/bbk_cli
UAP-AC-Proe870-BZ.v4.3.28# /tmp/bbk_cli
-ash: /tmp/bbk_cli: not found
UAP-AC-Proe870-BZ.v4.3.28# ldd /tmp/bbk_cli
        /lib/ld.so.1 (0x77636000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x774e4000)
        libm.so.6 => /lib/ld.so.1 (0x77636000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x774c0000)
        libc.so.6 => /lib/ld.so.1 (0x77636000)
UAP-AC-Proe870-BZ.v4.3.28# ls -l /lib/ld.so.1
ls: /lib/ld.so.1: No such file or directory
UAP-AC-Proe870-BZ.v4.3.28# cat /proc/cpuinfo
system type             : Qualcomm Atheros QCA956X ver 1 rev 0
machine                 : Ubiquiti Networks Inc. (c) gen2
processor               : 0
cpu model               : MIPS 74Kc V5.0
BogoMIPS                : 385.84
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp dsp2
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

UAP-AC-Proe870-BZ.v4.3.28#
```

I found one promising symlink in /lib to try to get it to find a suitable library, unfortunately I then got another error:

```
UAP-AC-Proe870-BZ.v4.3.28# ls -l /lib/*ld*so*
lrwxrwxrwx    1 Admin    root             7 Aug 30  2018 /lib/ld-musl-mips-sf.so.1 -> libc.so
UAP-AC-Proe870-BZ.v4.3.28# ln -s /lib/ld-musl-mips-sf.so.1 /lib/ld.so.1
UAP-AC-Proe870-BZ.v4.3.28# /tmp/bbk_cli
Illegal instruction (core dumped)
```

The error message "Illegal instruction" is suggesting to me that perhaps the pre-compiled MIPS binaries that are on the site are using some CPU instructions that are not available on my particular device (a Unifi UAC AP Pro Gen2). Unfortunately, this is all I can see without a development environment available on the machine. That, or my approach of symlinking what looks to be an ld.so is just wrong for some reason that I don't understand.

To try to work the problem, I was trying to see if I could find some instructions for how to cross-compile my own MIPS binaries, maybe tweak a few compiler flags, but I found no instructions or any obvious affordances in the Makefiles (after a quick scan) for how to do cross-compiles.

To work this problem I'd like to know how do produce MIPS binaries. Specifically, I'd try to see if I can produce a statically linked binary, and maybe target a smaller ISA? (Not sure which one you're targeting with your binaries, and I know almost nothing about the MIPS ISAs). Do you do some kind of cross-compilation that's not obvious to me how to do (and in that case do you have any pointers?), or do you just do it on MIPS hardware / emulator?

**Comment by initgoran** [comment]
The Makefile has been updated to make cross compilation easier.
To build, first load your cross compilation environment, setting variables like CXX and CXXFLAGS.
Then build using make.
