### ISSUE TITLE
Consider doing versioned releases

### ISSUE THREAD

**Issue by ankarhem** [dotse/bbk#8]
By doing versioned releases it will allow it to be added to package managers like a formula for brew etc.
As some (or all?) have a requirement like this one (copied from [here](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#basic-instructions))

    has a stable, tagged version (i.e. not just a GitHub repository with no versions)

**Comment by initgoran** [comment]
Yes, we will tag source releases from now on, starting with version BBK_CLI_1.2.1.
